FROM openjdk:8-jdk

RUN git clone https://github.com/fernandoccsvzla/courses-devops-project-java-dogs.git

WORKDIR courses-devops-project-java-dogs

RUN ./gradlew build

EXPOSE 8080

CMD ./gradlew bootRun